variable "region_name" {}
variable "vpc-cidr_block" {}
variable "vpc_tags" {}
variable "subnet-cidr_block" {}
variable "subnet_az" {}
variable "Subnet_tag" {}
variable "igw_tag" {}
variable "rt_cidr_block" {}
variable "rt_tag" {}
variable "ec2_az" {}
variable "ec2_type" {}
variable "key_name" {}